### ISSUE TITLE
useKindeClient can't import on server side

### ISSUE THREAD

**Issue by uyloal** [nuxt-modules/kinde#111]
`useKindeClinet` error added to nuxt client composables. 

Using `addServerImports` or `[addServerImportsDir](https://nuxt.com/docs/api/kit/nitro#addserverimportsdir)` maybe fix it

error code: [module.ts:132](https://github.com/nuxt-modules/kinde/blob/8856d40d6f7d568840f3739a611cb7ba91b5e90d/src/module.ts#L132)

Type error in API:
![image](https://github.com/nuxt-modules/kinde/assets/37807381/26cb32e1-7efa-4a06-b171-6d77037c2e28)

No type error in page
![image](https://github.com/nuxt-modules/kinde/assets/37807381/46210254-2add-48d4-b8ce-34096e18cbd5)

**Comment by Keyvitia** [comment]
By looking at the kinde.ts middleware source code, it seems kinde client is available at the event.context.
```typescript
export default defineEventHandler(async (event) => {
  const sessionManager = await createSessionManager(event)
  const kindeContext = { sessionManager } as Record<string, unknown>
  const kindeClient = getKindeClient()
  for (const _key in kindeClient) {
    const key = _key as keyof typeof kindeClient
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    kindeContext[key] = (kindeClient[key] as any).bind(kindeClient, sessionManager)
  }
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  event.context.kinde = kindeContext as any
})
```

**Comment by DanielRivers** [comment]
Hi @uyloal,

As @Keyvitia pointed out, the composable is not available on server side routes. 

We expose the Kinde instance in `event.context.kinde` everything is available there
