### ISSUE TITLE
User information available on server 

### ISSUE THREAD

**Issue by isakgustavsen** [nuxt-modules/kinde#122]
Hello

Looking at using the Managment api, but it would be really useful to have the user information(mainly ID) available in event.context.kinde. It is possible to send it as a param, but just having it there would be nice

**Comment by DanielRivers** [comment]
You can get the user ID like this

```javascript
const user = await event.context.kinde.getUser();
user.id // this holds the user
```

Is this sufficient for your needs @isakgustavsen ?

**Comment by DanielRivers** [comment]
Closing this issue, if you need further help please feel free to reach out.,
