### ISSUE TITLE
Hardcoded password

### ISSUE THREAD

**Issue by nhedger** [nuxt-modules/kinde#14]
Hey,

I was browsing the code and stumbled upon a hardcoded password, so I thought I'd let you know in case you missed it.

https://github.com/nuxt-modules/kinde/blob/0a1641d7753e37d2d695610a9a32bbceb7abb887/src/runtime/server/middleware/kinde.ts#L25

**Comment by VeryKinde** [comment]
Hey @nhedger!

This looks like a dummy password, but we will amend and push something out to make it more clear in the code.
