### ISSUE TITLE
Protect Nuxt (Nitro) API routes

### ISSUE THREAD

**Issue by Smart-Ace-Designs** [nuxt-modules/kinde#56]
Is there a way to use Kinde to protect Nuxt API routes in the "/server/api" folder?  I was able to do this with sidebase next-auth like this:

```js
import { getServerSession } from "#auth";

export default defineEventHandler(async (event) => {
  const session = await getServerSession(event);
  if (!session) {
    return { status: "unauthenticated" };
  }
  return {status: "authenticated"};
});
```

But I am trying to get away from using sidebase and checking out a hosted solution like Kinde instead.  The only thing I could find so far is the "useKindeClient" composable which mentions "Server Only" in description but I could not find any further documentation on how to actually use it.  Am I on the right track with that...or is that something completely different and would not be used for api route protection?

I am pretty new at this, so my apologies if I am not using all the correct terminology.
Thanks.

**Comment by Smart-Ace-Designs** [comment]
```js
export default defineEventHandler(async (event) => {
  const isAuthenticated = await event.context.kinde.isAuthenticated();
  if (!isAuthenticated) {
    return;
  }
  // Do some stuff
});
```

**Comment by faststare08** [comment]
how about middleware api?

**Comment by muneebbug** [comment]
> ```js
> export default defineEventHandler(async (event) => {
>   const isAuthenticated = await event.context.kinde.isAuthenticated();
>   if (!isAuthenticated) {
>     return;
>   }
>   // Do some stuff
> });
> ```

this does not work in ssr. when I try to run this, it says unauthenticated

this is my `index.vue`
```vue
<script setup lang="ts"> 
const {data} = await useAsyncData('index', () => $fetch('/api/test'))
console.log(data.value?.body)
</script>
```

this is `/server/api/test.get.ts`

```javascript
export default defineEventHandler(async (event) => {
  const isAuthenticated = await event.context.kinde.isAuthenticated();
  return {
    statusCode: isAuthenticated ? 200 : 401,
    body: isAuthenticated ? 'Authenticated' : 'Not authenticated',
  }
})

```
